
link_in_bot = "@Library_full_info_bot (https://t.me/Library_full_info_bot)"


library_descriptions = {
    "time": "Бібліотека time дозволяє працювати з часом та датами, наприклад, вимірювати час виконання коду або встановлювати затримки.",
    "datetime": "Бібліотека datetime забезпечує функції для роботи з датами і часом з точністю до мікросекунд.",
    "random": "Бібліотека random надає функції для генерації випадкових чисел та вибірки випадкових елементів.",
    "math": "Бібліотека math містить базові математичні функції, такі як синус, косинус, логарифми і факторіали.",
    "statistics": "Бібліотека statistics дозволяє обчислювати статистичні значення, як-от середнє, медіана, дисперсія тощо.",
    "os": "Бібліотека os дозволяє працювати з операційною системою, наприклад, керувати файлами та змінними середовища.",
    "sys": "Бібліотека sys забезпечує доступ до змінних та функцій, що взаємодіють із системою та інтерпретатором Python.",
    "json": "Бібліотека json надає інструменти для роботи з форматом JSON, включаючи серіалізацію та десеріалізацію даних.",
    "re": "Бібліотека re дозволяє використовувати регулярні вирази для пошуку і обробки тексту.",
    "collections": "Бібліотека collections містить додаткові структури даних, такі як deque, Counter, OrderedDict, namedtuple.",
    "itertools": "Бібліотека itertools містить інструменти для створення ітераторів для ефективної обробки даних у циклах.",
    "functools": "Бібліотека functools містить інструменти для роботи з функціями, зокрема, кешування і часткове застосування.",
    "operator": "Бібліотека operator забезпечує доступ до стандартних операцій у вигляді функцій для зручності роботи з ними.",
    "pathlib": "Бібліотека pathlib надає об'єктно-орієнтований підхід для роботи з файловими шляхами.",
    "fileinput": "Бібліотека fileinput забезпечує зручний доступ до обробки текстових файлів.",
    "io": "Бібліотека io дозволяє здійснювати операції введення і виведення, включаючи роботу з текстовими та байтовими потоками.",
    "shutil": "Бібліотека shutil містить функції для роботи з файлами та каталогами, наприклад, копіювання і переміщення файлів.",
    "glob": "Бібліотека glob дозволяє знаходити файли за шаблонами з використанням символів підстановки.",
    "argparse": "Бібліотека argparse надає інструменти для обробки аргументів командного рядка.",
    "configparser": "Бібліотека configparser дозволяє працювати з конфігураційними файлами у форматі INI.",
    "logging": "Бібліотека logging дозволяє вести журнал подій, щоб зручно відстежувати виконання програми.",
    "hashlib": "Бібліотека hashlib містить алгоритми хешування, такі як MD5 і SHA для забезпечення цілісності даних.",
    "uuid": "Бібліотека uuid дозволяє генерувати унікальні ідентифікатори.",
    "csv": "Бібліотека csv надає можливості для читання і запису файлів у форматі CSV.",
    "pickle": "Бібліотека pickle дозволяє серіалізувати та десеріалізувати об'єкти Python.",
    "copy": "Бібліотека copy містить функції для копіювання об'єктів, включаючи глибоке копіювання.",
    "heapq": "Бібліотека heapq дозволяє працювати з чергою з пріоритетом на основі структури heap.",
    "bisect": "Бібліотека bisect містить функції для ефективного вставлення і пошуку елементів у відсортованих списках.",
    "array": "Бібліотека array дозволяє створювати масиви з однорідних даних.",
    "zipfile": "Бібліотека zipfile дозволяє працювати з ZIP-архівами для стиснення і розпаковування файлів.",
    "tarfile": "Бібліотека tarfile дозволяє створювати та обробляти TAR-архіви.",
    "tempfile": "Бібліотека tempfile дозволяє створювати тимчасові файли і каталоги.",
    "getopt": "Бібліотека getopt забезпечує обробку аргументів командного рядка у форматі, схожому на C.",
    "subprocess": "Бібліотека subprocess дозволяє виконувати зовнішні команди і взаємодіяти з ними.",
    "threading": "Бібліотека threading дозволяє реалізувати багатопотоковість для паралельного виконання коду.",
    "multiprocessing": "Бібліотека multiprocessing дозволяє створювати процеси для паралельного виконання коду.",
    "socket": "Бібліотека socket дозволяє працювати з мережевими з'єднаннями за допомогою сокетів.",
    "enum": "Бібліотека enum забезпечує підтримку перелічуваних типів для створення перерахувань.",
    "struct": "Бібліотека struct дозволяє працювати з C-структурами і виконувати обробку байтових даних.",
    "weakref": "Бібліотека weakref дозволяє створювати слабкі посилання на об'єкти, які не запобігають їх збиранню сміття."
}


full_info_library = {
    "time": "https://docs.python.org/3/library/time.html",
    "datetime": "https://docs.python.org/3/library/datetime.html",
    "random": "https://docs.python.org/3/library/random.html",
    "math": "https://docs.python.org/3/library/math.html",
    "statistics": "https://docs.python.org/3/library/statistics.html",
    "os": "https://docs.python.org/3/library/os.html",
    "sys": "https://docs.python.org/3/library/sys.html",
    "json": "https://docs.python.org/3/library/json.html",
    "re": "https://docs.python.org/3/library/re.html",
    "collections": "https://docs.python.org/3/library/collections.html",
    "itertools": "https://docs.python.org/3/library/itertools.html",
    "functools": "https://docs.python.org/3/library/functools.html",
    "operator": "https://docs.python.org/3/library/operator.html",
    "pathlib": "https://docs.python.org/3/library/pathlib.html",
    "fileinput": "https://docs.python.org/3/library/fileinput.html",
    "io": "https://docs.python.org/3/library/io.html",
    "shutil": "https://docs.python.org/3/library/shutil.html",
    "glob": "https://docs.python.org/3/library/glob.html",
    "argparse": "https://docs.python.org/3/library/argparse.html",
    "configparser": "https://docs.python.org/3/library/configparser.html",
    "logging": "https://docs.python.org/3/library/logging.html",
    "hashlib": "https://docs.python.org/3/library/hashlib.html",
    "uuid": "https://docs.python.org/3/library/uuid.html",
    "csv": "https://docs.python.org/3/library/csv.html",
    "pickle": "https://docs.python.org/3/library/pickle.html",
    "copy": "https://docs.python.org/3/library/copy.html",
    "heapq": "https://docs.python.org/3/library/heapq.html",
    "bisect": "https://docs.python.org/3/library/bisect.html",
    "array": "https://docs.python.org/3/library/array.html",
    "zipfile": "https://docs.python.org/3/library/zipfile.html",
    "tarfile": "https://docs.python.org/3/library/tarfile.html",
    "tempfile": "https://docs.python.org/3/library/tempfile.html",
    "getopt": "https://docs.python.org/3/library/getopt.html",
    "subprocess": "https://docs.python.org/3/library/subprocess.html",
    "threading": "https://docs.python.org/3/library/threading.html",
    "multiprocessing": "https://docs.python.org/3/library/multiprocessing.html",
    "socket": "https://docs.python.org/3/library/socket.html",
    "enum": "https://docs.python.org/3/library/enum.html",
    "struct": "https://docs.python.org/3/library/struct.html",
    "weakref": "https://docs.python.org/3/library/weakref.html",
}